RaspBerryWebAppPro/Models/Relay.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RaspBerryWebAppPro.Models
{
    public class Relay
    {
        public Guid Id { get; set; }
        public Guid DeviceId { get; set; }

        public int Index { get; set; }
        public string Name { get; set; }    

        public virtual Device Device { get; set; }
        public virtual ICollection<RelayEvent> RelayEvents { get; set; }
    }
}

RaspBerryWebAppPro/Controllers/DevicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RaspBerryWebAppPro.Models;

namespace RaspBerryWebAppPro.Controllers
{
    public class DevicesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Devices
        public ActionResult Index()
        {
            return View(db.Devices.ToList());
        }

        // GET: Devices/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = db.Devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
        
            var relays = db.Relays.Where(x => x.DeviceId == id.Value).ToList<Relay>();
            device.Relays = relays;
            return View(device);
        }

        // GET: Devices/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Devices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,devicenumber,Name,IsSuccess")] Device device)
        {
            if (ModelState.IsValid)
            {
                device.Id = Guid.NewGuid();
                db.Devices.Add(device);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(device);
        }

        // GET: Devices/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = db.Devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            return View(device);
        }

        // POST: Devices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,SerialNumber,Name")] Device device)
        {
            if (ModelState.IsValid)
            {
                db.Entry(device).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(device);
        }

        // GET: Devices/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = db.Devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            return View(device);
        }

        // POST: Devices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Device device = db.Devices.Find(id);
            db.Devices.Remove(device);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RaspBerryWebAppPro/Controllers/RelayEventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RaspBerryWebAppPro.Models;

namespace RaspBerryWebAppPro.Controllers
{
    public class RelayEventsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();


        // GET: RelayEvents/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RelayEvent relayEvent = db.RelayEvents.Find(id);
            if (relayEvent == null)
            {
                return HttpNotFound();
            }
            return View(relayEvent);
        }

        // GET: RelayEvents/Create
        public ActionResult Create(Guid id)
        {
            ViewData["relayparentid"] = id;
            RelayEvent eventToCreate = new RelayEvent();
            eventToCreate.RelayId = id;
            eventToCreate.StartTime = DateTime.Now;
            eventToCreate.DurationInMinutes = 15;
            eventToCreate.EndTime = eventToCreate.StartTime.AddMinutes(15);
            return View(eventToCreate);
        }

        // POST: RelayEvents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,RelayId,StartTime,EndTime,DurationInMinutes")] RelayEvent relayEvent)
        {
            if (ModelState.IsValid)
            {
                relayEvent.Id = Guid.NewGuid();

                db.RelayEvents.Add(relayEvent);
                db.SaveChanges();

                return RedirectToAction("Details", "Relays", new { id = relayEvent.RelayId });

            }

            return View(relayEvent);
        }

        // GET: RelayEvents/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RelayEvent relayEvent = db.RelayEvents.Find(id);
            if (relayEvent == null)
            {
                return HttpNotFound();
            }
            return View(relayEvent);
        }

        // POST: RelayEvents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,RelayID,StartTime,EndTime,DurationInMinutes")] RelayEvent relayEvent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(relayEvent).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Details", "Relays", new { id = relayEvent.RelayId });


            }
            return View(relayEvent);
        }

        // GET: RelayEvents/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RelayEvent relayEvent = db.RelayEvents.Find(id);
            if (relayEvent == null)
            {
                return HttpNotFound();
            }
            return View(relayEvent);
        }

        // POST: RelayEvents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            RelayEvent relayEvent = db.RelayEvents.Find(id);
            db.RelayEvents.Remove(relayEvent);
            db.SaveChanges();
            return RedirectToAction("Details", "Relays", new { id = relayEvent.RelayId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RaspBerryWebAppPro/Controllers/RelaysController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RaspBerryWebAppPro.Models;

namespace RaspBerryWebAppPro.Controllers
{
    public class RelaysController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Relays/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Relay relay = db.Relays.Find(id);
            if (relay == null)
            {
                return HttpNotFound();
            }
      
            var relayEvents = db.RelayEvents.Where(x => x.RelayId == id.Value).ToList<RelayEvent>();
            relay.RelayEvents = relayEvents;
            return View(relay);
        }

        // GET: Relays/Create
        public ActionResult Create(Guid id)
        {
            ViewData["deviceparentid"] = id;
            Relay relay = new Relay();
            relay.Id = Guid.NewGuid();
            relay.DeviceId = id;
            return View(relay);
        }

        // POST: Relays/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,DeviceId")] Relay relay)
        {
            if (ModelState.IsValid)
            {
                relay.Id = Guid.NewGuid();
                relay.Index = GetFreeIndex(relay);
                db.Relays.Add(relay);
                db.SaveChanges();
                return RedirectToAction("Details", "Devices", new { id = relay.DeviceId });
            }

            return View(relay);
        }

        private int GetFreeIndex(Relay relay)
        {
            var relays = db.Relays.Where(x => x.DeviceId == relay.DeviceId).ToList<Relay>();

            for (int i = 0; i <= relays.Count(); i++)
            {
                if (!relays.Where(x => x.Index != i).Any())
                {
                    return i;
                }

            }

            return relays.Count();
        }

        // GET: Relays/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Relay relay = db.Relays.Find(id);
            if (relay == null)
            {
                return HttpNotFound();
            }
            return View(relay);
        }

        // POST: Relays/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Index,Name,DeviceID")] Relay relay)
        {
            if (ModelState.IsValid)
            {
                db.Entry(relay).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "Devices", new { id = relay.DeviceId });
            }
            return View(relay);
        }

        // GET: Relays/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Relay relay = db.Relays.Find(id);
            if (relay == null)
            {
                return HttpNotFound();
            }
            return View(relay);
        }

        // POST: Relays/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Relay relay = db.Relays.Find(id);
            db.Relays.Remove(relay);
            db.SaveChanges();
            return RedirectToAction("Details", "Devices", new { id = relay.DeviceId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RaspBerryWebAppPro/Views/Relays/Create.cshtml
@model RaspBerryWebAppPro.Models.Relay

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @*@Html.Hidden("DeviceID", ViewData["deviceparentid"])*@
    @Html.Hidden("DeviceID", Model.DeviceId)
    <div class="form-horizontal">
        <h4>Relay</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

RaspBerryWebAppPro/Views/Relays/Delete.cshtml
@model RaspBerryWebAppPro.Models.Relay

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Relay</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Index)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Index)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeviceId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeviceId)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" onclick="javascript: return confirm('Are you sure you wish to delete this item?');" />

        </div>
    }
</div>

RaspBerryWebAppPro/Views/Relays/Details.cshtml
@using RaspBerryWebAppPro.Models
@using Newtonsoft.Json
@model RaspBerryWebAppPro.Models.Relay
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Relay</h4>
    <hr />
    @Html.ActionLink("Edit Relay", "Edit", new { id = Model.Id })


    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Index)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Index)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeviceId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeviceId)
        </dd>
    </dl>


    <br />



    <table class="table">
        <tr>
            <th>
                StartTime
            </th>
            <th>
                Duration
            </th>

            <th></th>
        </tr>

        @foreach (RelayEvent relayevent in Model.RelayEvents)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => relayevent.StartTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => relayevent.DurationInMinutes)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "RelayEvents", new { id = relayevent.Id }, null) |
                    @Html.ActionLink("Details", "Details", "RelayEvents", new { id = relayevent.Id }, null) |
                    @Html.ActionLink("Delete", "Delete", "RelayEvents", new { id = relayevent.Id }, null)
                </td>
            </tr>
        }

    </table>




    <br />
    @Html.ActionLink("+ RelayEvent", "Create", "RelayEvents", new { id = Model.Id }, null)
    <br />
</div>
<p>
    @Html.ActionLink("Back to List of relays", "Details", "Devices", new { id = Model.DeviceId }, null)
</p>

<script type="text/javascript">



$(document).ready(function () {
    @*var aa="";
    var data = @Html.Raw(JsonConvert.SerializeObject(this.Model));
    debugger;
    alert(data.Relay.Name);*@
    });
</script>

RaspBerryWebAppPro/Views/Relays/Edit.cshtml
@model RaspBerryWebAppPro.Models.Relay

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Relay</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Index, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Index, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Index, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeviceId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeviceId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeviceId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>